eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@eureka.zyxx.com:8761/eureka/
      
#Redis
spring:
  redis:
    host: redis.zyxx.com
    #password: 123
    port: 6379
  zipkin:
    base-url: http://zipkin.zyxx.com:9411
  sleuth:
    sampler:
      percentage:1.0