server:
  port: 8769
spring:
  profiles:
    active: dev
  application:
    name: gateway-microservice
zuul:
  routes:
    user-api:
      path: /user-api/**
      serviceId: user-microservice
    product-api:
      path: /product-api/**
      serviceId: product-microservice
    stock-api:
      path: /stock-api/**
      serviceId: stock-microservice    
    gateway-api:
      path: /gateway-api/**
      serviceId: gateway-microservice
    order-api:
      path: /order-api/**
      serviceId: order-microservice
    oms-api:
      path: /oms-api/**
      serviceId: oms-microservice
    pay-api:
      path: /pay-api/**
      serviceId: pay-microservice
    permissions-api:
      path: /permissions-api/**
      serviceId: permissions-microservice
    tms-api:
      path: /tms-api/**
      serviceId: tms-microservice
    wms-api:
      path: /wms-api/**
      serviceId: wms-microservice
  add-host-header: true
feign:
  hystrix:
    enabled: true
ribbon:  
  ReadTimeout: 60000
  ConnectTimeout: 60000